<?php
/**
 * BookmarksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EveClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EveClient;

use \EveClient\Configuration;
use \EveClient\ApiException;
use \EveClient\ObjectSerializer;

/**
 * BookmarksApiTest Class Doc Comment
 *
 * @category Class
 * @package  EveClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookmarksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCharactersCharacterIdBookmarks
     *
     * List bookmarks.
     *
     */
    public function testGetCharactersCharacterIdBookmarks()
    {
    }

    /**
     * Test case for getCharactersCharacterIdBookmarksFolders
     *
     * List bookmark folders.
     *
     */
    public function testGetCharactersCharacterIdBookmarksFolders()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdBookmarks
     *
     * List corporation bookmarks.
     *
     */
    public function testGetCorporationsCorporationIdBookmarks()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdBookmarksFolders
     *
     * List corporation bookmark folders.
     *
     */
    public function testGetCorporationsCorporationIdBookmarksFolders()
    {
    }
}
