<?php
/**
 * UserInterfaceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EveClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.3.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EveClient;

use \EveClient\Configuration;
use \EveClient\ApiException;
use \EveClient\ObjectSerializer;

/**
 * UserInterfaceApiTest Class Doc Comment
 *
 * @category Class
 * @package  EveClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserInterfaceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for postUiAutopilotWaypoint
     *
     * Set Autopilot Waypoint.
     *
     */
    public function testPostUiAutopilotWaypoint()
    {
    }

    /**
     * Test case for postUiOpenwindowContract
     *
     * Open Contract Window.
     *
     */
    public function testPostUiOpenwindowContract()
    {
    }

    /**
     * Test case for postUiOpenwindowInformation
     *
     * Open Information Window.
     *
     */
    public function testPostUiOpenwindowInformation()
    {
    }

    /**
     * Test case for postUiOpenwindowMarketdetails
     *
     * Open Market Details.
     *
     */
    public function testPostUiOpenwindowMarketdetails()
    {
    }

    /**
     * Test case for postUiOpenwindowNewmail
     *
     * Open New Mail Window.
     *
     */
    public function testPostUiOpenwindowNewmail()
    {
    }
}
